# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class HomebrewKexpose < Formula
  desc "Macos-focused terminal ui (tui) application for discovering kubernetes service"
  homepage "https://github.com/donsolly/homebrew-kexpose"
  url "https://github.com/donsolly/homebrew-kexpose/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "c989c3b7add36e07826ce69e9a7c872f1600cad1ea2497d7a9ff0201c9c4b00c"

  on_macos do
  end

  def install
    bin.install "kexpose"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kexpose --version")
  end
end
