# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class HomebrewKexpose < Formula
  desc "Macos-focused terminal ui (tui) application for discovering kubernetes service"
  homepage "https://github.com/donsolly/homebrew-kexpose"
  url "https://github.com/donsolly/homebrew-kexpose/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "2bf518d6e737b5aa4061581448c6d0f8838bd269ecc3d28f7b4061f8fc943d19"

  on_macos do
  end

  def install
    bin.install "kexpose"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kexpose --version")
  end
end
